### PR TITLE
Use pointingPreciseTimeout in DraggingHandle

### LINKED ISSUE #6767: ArrowShapeUtil pointingPreciseTimeout is not applied
### What happened?

This is related to https://github.com/tldraw/tldraw/issues/6764 and https://github.com/tldraw/tldraw/issues/6765 where we'd like to change how the arrow snapping looks and feels. 
---

My understanding is that `hoverPreciseTimeout` and `pointingPreciseTimeout` should change the amount of time needed to hover the start and endpoints of the target shape before `isPrecise` is applied.   

However, I've tried to configure ArrowShapeUtil's `pointingPreciseTimeout` doesn't work

Here's an example of defaults being used which to my understanding is 
```		
hoverPreciseTimeout: 600,
pointingPreciseTimeout: 320,
```
https://github.com/user-attachments/assets/b7912eab-b750-41ab-99f7-e896826064a9

But, when applying 3 seconds timeout to both, the pointingPreciseTimeout doesn't seem to work:

https://github.com/user-attachments/assets/60a2a982-341b-4222-ab23-76780478cca5

### How can we reproduce the bug?

Configure pointingPreciseTimeout to have no delay, or a long delay, without it seeming to have an effect. 
```
ArrowShapeUtil.configure({
    pointingPreciseTimeout: 0, // this doesn't seem to work
})

ArrowShapeUtil.configure({
    pointingPreciseTimeout: 3000, // this doesn't seem to work
})
```

### What browsers are you seeing the problem on?

_No response_

### Where did this happen?

The developer package

### Contact Details

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ds300**
This fixes #6767 – we still have some hard-coded arrow logic in the select tool which was not using the arrow shape util's configuration values around precision interactions.

### Change type

- [x] `bugfix`

### Test plan

1. Create a shape...
2.

- [x] Unit tests
- [ ] End to end tests

### Release notes

- Fixed a bug where the Arrow tool's `pointingPreciseTimeout` option was not being respected.

### CODE REVIEW

File: packages/tldraw/src/lib/tools/SelectTool/childStates/DraggingHandle.tsx [hunk 1]
```diff
@@ -139,6 +139,9 @@ export class DraggingHandle extends StateNode {
 
 	// Only relevant to arrows
 	private resetExactTimeout() {
+		const arrowUtil = this.editor.getShapeUtil<any>('arrow')
+		const timeoutValue = (arrowUtil.options as any)?.pointingPreciseTimeout ?? 750
```
Comment (SomeHats) [inline packages/tldraw/src/lib/tools/SelectTool/childStates/DraggingHandle.tsx]:
```suggestion
		const arrowUtil = this.editor.getShapeUtil<ArrowShapeUtil>('arrow')
		const timeoutValue = arrowUtil.options.pointingPreciseTimeout
```

**Review by SomeHats — APPROVED** [review]

File: packages/tldraw/src/lib/tools/SelectTool/childStates/DraggingHandle.tsx (hunk 1 above)
Comment (ds300) [reply packages/tldraw/src/lib/tools/SelectTool/childStates/DraggingHandle.tsx]: ah right, for some reason I though this was in the editor package
