### PR TITLE
fix(memory): clean up module-level state leaks after editor unmount

### LINKED ISSUE #8440: Module-level state causes memory leaks after editor unmount
Several module-level caches, globals, and debounced/throttled functions retain `Editor`, `Store`, or `TLLocalSyncClient` references after the editor unmounts, preventing garbage collection. This was originally reported in #8430 for the `updateHoveredShapeId` throttle, but the pattern appears in multiple other places.

#8439 fixes the `updateHoveredShapeId` case. This issue tracks the remaining cases.

### 1. `window.tlsync` retains `TLLocalSyncClient` (and `Store`) — HIGH

**File:** `packages/editor/src/lib/utils/sync/TLLocalSyncClient.ts:105`

The constructor unconditionally sets `window.tlsync = this`. The `close()` method (line 261) runs disposables but never clears `window.tlsync`. After unmount, the closed client and its entire retained graph (Store, LocalIndexedDb, BroadcastChannel, subscriptions) cannot be GC'd.

```ts
// constructor
if (typeof window !== 'undefined') {
    ;(window as any).tlsync = this
}
```

**Fix:** Clear `window.tlsync` in `close()`, or guard it behind `process.env.NODE_ENV !== 'production'`.

### 2. `window.tlsync` retains `TLSyncClient` (and `Store`) — HIGH

**File:** `packages/sync-core/src/lib/TLSyncClient.ts:538`

Same pattern as above in the multiplayer sync client. `TLSyncClient.close()` (line 824) does not clear `window.tlsync`.

**Fix:** Same as above.

### 3. Module-level `debounce` in bookmarks retains `Editor` — HIGH

**File:** `packages/tldraw/src/lib/shapes/bookmark/bookmarks.ts:87`

```ts
const createBookmarkAssetOnUrlChange = debounce(async (editor: Editor, shape: TLBookmarkShape) => {
    if (editor.isDisposed) return
    // ...
}, 500)
```

This is the exact same class of bug as the `updateHoveredShapeId` throttle: a module-level `debounce()` that receives `editor` as an argument. The debounce stores `latestArgs` internally, retaining the Editor after unmount until the debounce fires (500ms). Additionally, `cancel()` in the debounce utility does not release retained args (see case 6).

**Fix:** Use per-editor debounced instances via `WeakMap<Editor, ...>`, same pattern as the `updateHoveredShapeId` fix.

### 4. `debounce.cancel()` does not release retained arguments — MEDIUM

**File:** `packages/utils/src/lib/debounce.ts:79-82`

```ts
fn.cancel = () => {
    if (!state) return
    clearTimeout(state.timeout)
    // state.latestArgs is NOT cleared
}
```

The `cancel()` method clears the timeout but does not null out `state` or `state.latestArgs`. Any caller that cancels a debounced function permanently retains the last arguments in the closure. This is a systemic issue that would affect any debounced function holding Editor references.

**Fix:** Set `state = undefined` in `cancel()`.

### 5. `ImageAlphaCache` — unbounded `Map` — MEDIUM

**File:** `packages/tldraw/src/lib/shapes/image/ImageAlphaCache.ts:68-70`

```ts
const alphaCache = new Map<string, AlphaData>()
const pending = new Set<string>()
```

Module-level `Map<string, AlphaData>` keyed by image URL, storing downsampled alpha channel data (`Uint8Array` up to 256×256 = 65KB per entry). This cache grows with every unique image loaded and is never cleared. Doesn't retain Editor references, but can accumulate significantly in image-heavy usage or across multiple editor instances.

**Fix:** Use a bounded cache (LRU or reset-on-limit like `stringHashCache`), or scope to editor lifetime.

### 6. `LocalIndexedDb.connectedInstances` static Set — MEDIUM

**File:** `packages/editor/src/lib/utils/sync/LocalIndexedDb.ts:104`

```ts
static connectedInstances = new Set<LocalIndexedDb>()
```

Instances added in constructor (line 107), removed in `close()` (line 132). If `close()` is not called (e.g. the owning `TLLocalSyncClient` leaks via `window.tlsync`), the instance stays in the static set forever. Secondary leak path from case 1.

**Fix:** Fixing case 1 largely resolves this, but defensive cleanup would help.

## Already safe

The following module-level caches were investigated and confirmed safe (all use `WeakMap` or `WeakCache`):

- `arrowBindingsCache`, `arrowInfoCache`, `labelSizeCache` — `WeakCache<Editor>`
- `pathCache`, `handlesCache` (line, geo shapes) — `WeakCache<shape>`
- `dvCache` (display values) — `WeakMap<TLShape>`
- `sizeCache` (text) — `createComputedCache` (WeakCache)
- `stringHashCache` (ImmutableMap) — bounded at 24K entries, no Editor refs
- Draw shape rendering — purely functional, no caching

## Change type

- [x] `bugfix`

### PR DESCRIPTION
**Pull request by MitjaBezensek**
In order to prevent `Editor`, `Store`, and sync client instances from being retained after unmount, this PR cleans up several module-level caches, globals, and debounced functions that hold references. Particularly impactful for apps that mount/unmount editors frequently (iOS WebViews hit memory limits). Closes #8440.

**`debounce.cancel()`** — sets `state = undefined` so `latestArgs` (and any captured Editor) are released on cancel. Previously only cleared the timeout.

**`window.tlsync`** — cleared in `close()` for both `TLLocalSyncClient` and `TLSyncClient`. Guarded with `=== this` to avoid clearing a newer client's reference.

**Bookmark debounce** — replaced module-level `debounce(editor, shape)` with per-editor instances via `WeakMap<Editor, ...>` (same pattern as the `updateHoveredShapeId` fix in #8439). Debouncer is GC'd with the editor.

**`LruCache`** — new `@tldraw/utils` class (~20 LOC) using `Map` insertion-order for O(1) LRU eviction. `fetchCache` (cap 200) and `alphaCache` (cap 500) now use `LruCache` instead of unbounded `Map`s, preventing unbounded growth while keeping hot entries warm.

### Change type

- [x] `bugfix`

### Test plan

1. Mount/unmount editor multiple times
2. Take heap snapshots, confirm Editor instances are GC'd
3. Verify bookmark URL unfurling still works after editor remount
4. Verify image alpha hit-testing works with many unique images

- [x] Unit tests
- [ ] End to end tests

### Release notes

- Fixed memory leaks from module-level state retaining editor references after unmount
- Added `LruCache` utility class for bounded caches with least-recently-used eviction

### API changes

- Added `LruCache<K, V>` class to `@tldraw/utils` with `get`, `set`, `has`, and `size`

### Code changes

| Section         | LOC change |
| --------------- | ---------- |
| Core code       | +60 / -8   |
| Tests           | +89 / -0   |
| Automated files | +13 / -0   |

### CODE REVIEW

File: packages/utils/src/lib/LruCache.ts [hunk 1]
```diff
@@ -0,0 +1,32 @@
+/** Simple LRU cache backed by a Map's insertion-order iteration. @public */
```
Comment (mimecuvalo) [inline packages/utils/src/lib/LruCache.ts:1]: huh i'm surpised we don't have one of these yet

File: packages/tldraw/src/lib/shapes/image/ImageAlphaCache.ts [hunk 2]
```diff
@@ -65,7 +65,7 @@ export function isImagePointTransparent(
 
 const MAX_SIZE = 256
 
-const alphaCache = new Map<string, AlphaData>()
+const alphaCache = new LruCache<string, AlphaData>(500)
```
Comment (mimecuvalo) [inline packages/tldraw/src/lib/shapes/image/ImageAlphaCache.ts]: 500 seems high?

File: packages/editor/src/lib/utils/sync/TLLocalSyncClient.ts [hunk 3]
```diff
@@ -262,6 +262,9 @@ export class TLLocalSyncClient {
 		this.debug('closing')
 		this.didDispose = true
 		this.disposables.forEach((d) => d())
+		if (typeof window !== 'undefined' && (window as any).tlsync === this) {
+			delete (window as any).tlsync
```
Comment (mimecuvalo) [inline packages/editor/src/lib/utils/sync/TLLocalSyncClient.ts:266]: huh TIL that we set this on the window obj

File: packages/editor/src/lib/exports/fetchCache.ts [hunk 4]
```diff
@@ -1,9 +1,7 @@
-import { FileHelpers, assert, fetch } from '@tldraw/utils'
+import { FileHelpers, LruCache, assert, fetch } from '@tldraw/utils'
 
-// TODO(alex): currently, this cache will grow unbounded. we should come up with a better strategy
-// for clearing items from the cache over time.
 export function fetchCache<T>(cb: (response: Response) => Promise<T>, init?: RequestInit) {
-	const cache = new Map<string, Promise<T | null>>()
+	const cache = new LruCache<string, Promise<T | null>>(200)
```
Comment (mimecuvalo) [inline packages/editor/src/lib/exports/fetchCache.ts]: 200 seems maybe high too, i think 100 is prbly fine

Comment (MitjaBezensek) [reply packages/editor/src/lib/exports/fetchCache.ts]: Adjusted.

File: packages/tldraw/src/lib/shapes/image/ImageAlphaCache.ts (hunk 2 above)
Comment (MitjaBezensek) [reply packages/tldraw/src/lib/shapes/image/ImageAlphaCache.ts]: Adjusted this as well.

File: packages/utils/src/lib/LruCache.ts (hunk 1 above)
Comment (MitjaBezensek) [reply packages/utils/src/lib/LruCache.ts:1]: Yeah 🤷‍♂️

File: packages/utils/src/lib/LruCache.ts [hunk 5]
```diff
@@ -0,0 +1,32 @@
...
+export class LruCache<K, V> {
+	private map = new Map<K, V>()
+	constructor(private maxSize: number) {}
+
+	get(key: K): V | undefined {
+		const value = this.map.get(key)
+		if (value !== undefined) {
```
Comment (mimecuvalo) [inline packages/utils/src/lib/LruCache.ts]: value _could_ be undefined if we wanted that in the cache (since this is a generic cache)


```suggestion
    if (!this.map.has(key)) return undefined
    const value = this.map.get(key)!
    this.map.delete(key)
    this.map.set(key, value)
    return value
```

File: packages/utils/src/lib/LruCache.ts [hunk 6]
```diff
@@ -0,0 +1,32 @@
...
+			// Evict oldest entry
+			this.map.delete(this.map.keys().next().value!)
+		}
+	}
+
+	has(key: K): boolean {
+		return this.map.has(key)
+	}
+
+	getSize(): number {
```
Comment (mimecuvalo) [inline packages/utils/src/lib/LruCache.ts]: AtomMap and AtomSet use `get size() {` - let's do the same here prbly

**Review by mimecuvalo — APPROVED** [review]
pre-approved 👍
