### PR TITLE
fix(ui): save input on blur in link editor + alt text editor

### LINKED ISSUE #7673: Clicking outside link edit dialog should save instead of cancel
## Summary

When editing a link (either on a shape via the Edit Link dialog or in rich text), clicking outside the dialog/input should save the current link value and close, rather than canceling and discarding changes.

## Current behavior

1. Select a shape with a URL property (e.g., geo shape)
2. Open the "Edit link" dialog
3. Enter or modify a URL
4. Click on the canvas background (outside the dialog)
5. **Result**: The dialog closes and changes are discarded

The same behavior occurs for the rich text link editor - clicking outside cancels instead of saving.

## Expected behavior

Clicking outside the dialog should be treated as "accept and continue" - the current link value should be saved before closing. This matches common UI patterns where clicking away from an input field typically confirms the change rather than canceling it.

## Use case

Users often click away from dialogs/inputs as a natural way to "finish" editing, expecting their changes to be saved. Having to explicitly click "Save" or press Enter is less intuitive, and accidentally clicking outside results in lost work.

### PR DESCRIPTION
**Pull request by mimecuvalo**
In order to prevent users from accidentally losing their link edits when clicking outside the rich text link editor and alt text editor, this PR makes clicking away save the current value instead of discarding it. Closes #7673.

### Change type

- [x] `improvement`

### Test plan

1. Create a geo shape and double-click to edit text
2. Type some text, select it, click the link button in the rich text toolbar
3. Type a URL (e.g. `example.com`)
4. Click away from the link input (on the canvas)
5. Verify the link is saved (text should be linked)
6. Re-enter the shape, select the linked text, click the link button
7. Press Escape - verify the link is NOT changed
8. Re-enter the shape, select the linked text, click the link button
9. Press Enter - verify the link is saved

- [ ] Unit tests
- [x] End to end tests

### Release notes

- Fix rich text link editor to save the link when clicking outside instead of discarding changes.

---

> [!NOTE]
> **Medium Risk**
> Adds global `pointerdown` handlers that auto-commit edits; mistakes here could cause unintended saves or event ordering issues in the UI, though scope is limited to toolbar editors.
> 
> **Overview**
> Prevents losing edits in the rich-text link editor and media alt-text editor by **auto-saving on click-away**: both `LinkEditor` and `AltTextEditor` now listen for `pointerdown` outside their respective toolbars and commit the current value (or remove the link if empty).
> 
> To support this, image/video toolbars share a new `.tlui-media__toolbar` class used for outside-click detection, and an e2e test is added to verify a link is saved when the user clicks outside the link input without pressing Enter.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 9773390a8abe439cbb2f9050b42ba29165c6eb9a. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: packages/tldraw/src/lib/ui/components/Toolbar/LinkEditor.tsx [hunk 1]
```diff
@@ -40,22 +40,39 @@ export function LinkEditor({ textEditor, value: initialValue, onClose }: LinkEdi
...
+			const toolbar = document.querySelector('.tlui-rich-text__toolbar')
+			if (toolbar?.contains(e.target as Node)) return
+			// If the pointer down is not in the toolbar, complete the link
+			if (value) {
+				handleLinkComplete(value)
+			} else {
+				handleRemoveLink()
+			}
+		}
+		document.addEventListener('pointerdown', handlePointerDown, { capture: true })
```
Comment (MitjaBezensek) [inline packages/tldraw/src/lib/ui/components/Toolbar/LinkEditor.tsx:73]: Think we now set these up on every keypress since `value` is a dependency. We could store it in a separate ref?

Comment (mimecuvalo) [reply packages/tldraw/src/lib/ui/components/Toolbar/LinkEditor.tsx:73]: ehh, i dunno, it's cheap to set/unset it. i'd rather not add a cached value in a ref. easy for it to get out-of-sync
