### PR TITLE
[Bug] Added visibility of clone tool

### LINKED ISSUE #368: [feature] Show tool-specific style options when tool is selected
Currently we only show the text style options when a text shape is selected. We should also show those style options when the text tool is selected, so that a user can select their style before creating a shape.

### PR DESCRIPTION
**Pull request by proful**
Added canClone flags for 
- Draw
- Rectangle
- Text

For other shapes, after cloning, target position is getting distorted.

---
Fix for show those style options when the text tool is selected
closes #368

### CODE REVIEW

File: packages/tldraw/src/components/TopPanel/StyleMenu/StyleMenu.tsx [hunk 1]
```diff
@@ -2,12 +2,7 @@ import * as React from 'react'
 import * as DropdownMenu from '@radix-ui/react-dropdown-menu'
 import { strokes, fills, defaultTextStyle } from '~state/shapes/shared/shape-styles'
 import { useTldrawApp } from '~hooks'
-import {
-  DMCheckboxItem,
-  DMContent,
-  DMRadioItem,
-  DMTriggerIcon,
-} from '~components/Primitives/DropdownMenu'
+import { DMCheckboxItem, DMContent, DMRadioItem } from '~components/Primitives/DropdownMenu'
```
Comment (proful) [inline packages/tldraw/src/components/TopPanel/StyleMenu/StyleMenu.tsx:5]: Removed unused DMTriggerIcon

**Comment by steveruizok** [comment]
Let's limit clone handles to just sticky notes for now. Maybe we'll add some further user-customization in the future for folks who want to be able to clone other things?

**Comment by steveruizok** [comment]
Thanks @proful !
