### PR TITLE
[docs] Fix missing Persistence page

### LINKED ISSUE #2826: [docs]: Persistence page is not showing
we have a bug in our addContent strategy that will overwrite a page if another page is added later with the same id. This is currently affecting our `persistence.mdx` page which is being overwritten by the `persistence/` example.

### PR DESCRIPTION
**Pull request by ds300**
Fixes #2826, extracted from #2680 

The problem is that we had two different articles whose ids were being derived as `persistence`, the `persistence.mdx` file and the `persistence/` example.

I've

1. Made it an error for two articles to have the same id
2. Renamed the `persistence/` article to `local-storage` since that's the API it's using.

### Change Type

- [ ] `patch` — Bug fix
- [ ] `minor` — New feature
- [ ] `major` — Breaking change
- [ ] `dependencies` — Changes to package dependencies[^1]
- [x] `documentation` — Changes to the documentation only[^2]
- [ ] `tests` — Changes to any test code only[^2]
- [ ] `internal` — Any other changes that don't affect the published package[^2]
- [ ] I don't know

[^1]: publishes a `patch` release, for devDependencies use `internal`
[^2]: will not publish a new version

### Test Plan

1. Add a step-by-step description of how to test your PR here.
3.

- [ ] Unit Tests
- [ ] End to end tests

### Release Notes

- Add a brief release note for your PR here.

### CODE REVIEW

File: apps/docs/utils/addContent.ts [hunk 1]
```diff
@@ -8,19 +8,19 @@ export async function addContentToDb(
 	content: GeneratedContent
 ) {
 	const sectionInsert = await db.prepare(
-		`REPLACE INTO sections (id, idx, title, description, path, sidebar_behavior) VALUES (?, ?, ?, ?, ?, ?)`
+		`INSERT INTO sections (id, idx, title, description, path, sidebar_behavior) VALUES (?, ?, ?, ?, ?, ?)`
```
Comment (steveruizok) [inline apps/docs/utils/addContent.ts:11]: Will these changes mean the db will have an error if the id is already there?

**Review by steveruizok — APPROVED** [review]

File: apps/docs/utils/addContent.ts (hunk 1 above)
Comment (ds300) [reply apps/docs/utils/addContent.ts:11]: yeah, but it clears the db before running so if there's something there already it's overwriting a different bit of content and is therefore an error we want to throw.

**Comment by steveruizok** [comment]
I vaguely remember choosing REPLACE instead of INSERT in order to avoid duplicated items in the database when editing files, but I can't reproduce any of those things, so we might as well land this one and then maybe keep an eye out?
