### PR TITLE
Fix some export bugs

### LINKED ISSUE #5020: [Bug]: Incorrect cropping when exporting scaled text within a frame
### What happened?

https://discord.com/channels/859816885297741824/1298906470892572733/1307279925413150750

Uploading Discord Developer Help Video.mov…

### How can we reproduce the bug?

_No response_

### What browsers are you seeing the problem on?

_No response_

### Where did this happen?

The tldraw.com website

### Contact Details

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by SomeHats**
Fix #5020, #5045 & an issue where running two exports at the same time could cause one not to correctly include the right fonts

### Change type

- [x] `bugfix`
- [ ] `improvement`
- [ ] `feature`
- [ ] `api`
- [ ] `other`

### Release notes

- Properly clip scaled text in frames when exporting
- Stop multiple concurrent exports from interfering with each-others fonts

### CODE REVIEW

File: packages/editor/src/lib/exports/ExportDelay.tsx [hunk 1]
```diff
@@ -27,6 +27,7 @@ export class ExportDelay {
 
 	private async resolvePromises() {
 		let lastLength = null
+		await sleep(1000)
```
Comment (mimecuvalo) [inline packages/editor/src/lib/exports/ExportDelay.tsx:30]: intended?
