### PR TITLE
fix (tldraw): kbd shortcut style updates

### LINKED ISSUE #8178: Hide selection UI when changing styles via keyboard shortcuts
When changing styles (color, fill, etc.) using the style panel, the selection UI (bounds, handles, resize controls) is temporarily hidden so the user can preview the change on the shape itself. This uses the `isChangingStyle` flag on the instance state, which hides selection foreground elements and auto-resets after ~1 second.

However, when using keyboard shortcuts to change styles (e.g., `alt+t` for white color, `alt+f` for fill), the selection UI is **not** hidden. The keyboard shortcut handlers in `actions.tsx` call `setStyleForSelectedShapes` / `setStyleForNextShapes` but never set `isChangingStyle: true`.

## Expected behavior

Using a keyboard shortcut to change a style should temporarily hide the selection UI, just like when changing styles via the style panel.

## Actual behavior

The selection bounds, handles, and resize controls remain visible when using keyboard shortcuts, making it harder to preview the style change on the shape.

## Steps to reproduce

1. Create a shape and select it
2. Use a keyboard shortcut to change a style (e.g., `alt+t` for white color)
3. Notice the selection UI stays visible
4. Compare: open the style panel and change the color there — the selection UI hides temporarily

### PR DESCRIPTION
**Pull request by danieljamesross**
Add `editor.updateInstanceState({ isChangingStyle: true })` to all style change
keyboard shortcuts in `packages/tldraw/src/lib/ui/context/actions.tsx`.

Closes #8178

- [x] `bugfix`
- [ ] `improvement`
- [ ] `feature`
- [ ] `api`
- [ ] `other`

Add `({ isChangingStyle: true })` to all kbd shortcut style updates

### CODE REVIEW

**Comment by kostyafarber** [comment]
nice! just need to add the cla

**Comment by danieljamesross** [comment]
I have read and agree to the Contributor License Agreement.

**Review by kostyafarber — APPROVED** [review]

File: packages/tldraw/src/lib/ui/context/actions.tsx [hunk 1]
```diff
@@ -1682,6 +1685,7 @@ export function ActionsProvider({ overrides, children }: ActionsProviderProps) {
 				isRequiredA11yAction: true,
 				onSelect: async (source) => {
 					if (!canApplySelectionAction()) return
+					editor.updateInstanceState({ isChangingStyle: true })
```
Comment (mimecuvalo) [inline packages/tldraw/src/lib/ui/context/actions.tsx]: actually, this one should be omitted. this is an a11y action just to help with tabbing over to the style panel, we shouldn't have the indicators disappear when this happens.

**Review by mimecuvalo — APPROVED** [review]
LGTM modulo one comment before landing pls!
