### PR TITLE
Fix tool overrides

### LINKED ISSUE #6320: Overriding a built-in tool doesn't work
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `tldraw@3.13.1` for the project I'm working on.

I have a custom implementation of the laser tool which uses a different cursor. I noticed that my custom cursor wasn't being used and traced the problem back to this small issue.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/tldraw/dist-esm/lib/Tldraw.mjs b/node_modules/tldraw/dist-esm/lib/Tldraw.mjs
index 6f0ba16..4b445a1 100644
--- a/node_modules/tldraw/dist-esm/lib/Tldraw.mjs
+++ b/node_modules/tldraw/dist-esm/lib/Tldraw.mjs
@@ -78,7 +78,7 @@ function Tldraw(props) {
   );
   const _tools = useShallowArrayIdentity(tools);
   const toolsWithDefaults = useMemo(
-    () => mergeArraysAndReplaceDefaults("id", allDefaultTools, _tools),
+    () => mergeArraysAndReplaceDefaults("id", _tools, allDefaultTools),
     [_tools]
   );
   const _imageMimeTypes = useShallowArrayIdentity(
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

### PR DESCRIPTION
**Pull request by ds300**
these were being merged in the wrong order

closes #6320 

### Change type

- [x] `bugfix`

### Release notes

- Fixed a bug where overriding builtin tools was not working.

### CODE REVIEW

File: packages/tldraw/src/lib/Tldraw.tsx [hunk 1]
```diff
@@ -147,7 +147,7 @@ export function Tldraw(props: TldrawProps) {
 
 	const _tools = useShallowArrayIdentity(tools)
 	const toolsWithDefaults = useMemo(
-		() => mergeArraysAndReplaceDefaults('id', allDefaultTools, _tools),
+		() => mergeArraysAndReplaceDefaults('id', _tools, allDefaultTools),
```
Comment (mimecuvalo) [inline packages/tldraw/src/lib/Tldraw.tsx:150]: admittedly i can see how this mistake can be made since in JS typically you do `[...defaults, ...overrides]` this function does the opposite which is maybe why it's a slight footgun
