### PR TITLE
fix(utils): prevent false positive multiple instances warning in dev mode

### LINKED ISSUE #4614: Multiple instances error after upgrading to v3
### What happened?

I'm using tldraw with Next.js, and I got the "multiple instances" error after I updated it to v3.1.0 (I also tried to do a clean install of modules). The error looks like

```
[tldraw] You have multiple instances of some tldraw libraries active. This can lead to bugs and unexpected behavior. 

This usually means that your bundler is misconfigured, and is importing the same library multiple times - usually once as an ES Module, and once as a CommonJS module.

The following libraries have been imported multiple times:
  • ❌ @tldraw/utils v3.1.0: 
      1. ES Modules
      2. ES Modules
  • ❌ @tldraw/state v3.1.0: 
      1. ES Modules
      2. ES Modules
  • ❌ @tldraw/store v3.1.0: 
      1. ES Modules
      2. ES Modules
  • ❌ @tldraw/validate v3.1.0: 
      1. ES Modules
      2. ES Modules
  • ❌ @tldraw/tlschema v3.1.0: 
      1. ES Modules
      2. ES Modules
  • ❌ @tldraw/sync-core v3.1.0: 
      1. ES Modules
      2. ES Modules
  • ❌ @tldraw/state-react v3.1.0: 
      1. ES Modules
      2. ES Modules
  • ❌ @tldraw/editor v3.1.0: 
      1. ES Modules
      2. ES Modules
  • ❌ tldraw v3.1.0: 
      1. ES Modules
      2. ES Modules
  • ❌ @tldraw/sync v3.1.0: 
      1. ES Modules
      2. ES Modules
```

My `package.json` looks like this (which is used by both the server and front-end, so both sync and sync-core are installed in the same place, removing them didn't remove the error message)

```
"dependencies": {
    "@tldraw/sync": "^3.1.0",
    "@tldraw/sync-core": "^3.1.0",
    "tldraw": "^3.1.0"
  }
```

I can confirm that this is the only place where I install the packages. I didn't modify the config file for Next.js.

I wonder if there are other possibilities for the cause of the issue. Thanks.

### How can we reproduce the bug?

Please see above.

### What browsers are you seeing the problem on?

_No response_

### Where did this happen?

The developer package

### Contact Details

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by steveruizok**
In order to fix a false positive "multiple instances" warning that fires in Next.js dev mode, this PR deduplicates registrations in `registerTldrawLibraryVersion()`.

When Next.js re-evaluates modules on page refresh, each tldraw package re-registers itself via `registerTldrawLibraryVersion()`. Since `globalThis.__TLDRAW_LIBRARY_VERSIONS__` persists across module re-evaluations, duplicate entries accumulate and trigger the "multiple instances" warning — even though only one copy of each library is loaded (all entries show the same version and same module type).

The fix skips registration when an identical entry (same name, version, and module type) already exists. Genuine conflicts (different versions or mixed ESM/CJS) are still detected correctly.

Closes #4614

### Change type

- [x] `bugfix`

### Test plan

1. Use tldraw in a Next.js app with dev mode
2. Refresh the page — the false "multiple instances" warning should no longer appear
3. Genuine version mismatches or ESM/CJS conflicts should still produce warnings

- [x] Unit tests

### Release notes

- Fixed false positive "multiple instances" warning in Next.js dev mode caused by module re-evaluation

---

> [!NOTE]
> **Low Risk**
> Small, well-scoped change to warning/dedup logic gated to Next.js dev mode with unit test coverage; main risk is inadvertently suppressing a real duplicate only under those conditions.
> 
> **Overview**
> Prevents false "multiple instances" warnings in Next.js *dev mode* by skipping re-registration when `registerTldrawLibraryVersion` sees an **exact duplicate** entry (same package, version, and module type) during Fast Refresh.
> 
> Adds `isNextjsDev()` gating (checks `NODE_ENV === 'development'` and presence of `__NEXT_DATA__`) so duplicate tracking and warnings still occur in non-Next.js environments, and updates tests to cover both the Next.js dev dedupe behavior and the unchanged non-dev duplicate warning.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit cc920c01d365539317e63c0fb542e6fc8d2d91fb. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: packages/utils/src/lib/version.ts [hunk 1]
```diff
@@ -93,6 +93,10 @@ export function registerTldrawLibraryVersion(name?: string, version?: string, mo
 	}
 
 	const info = getLibraryVersions()
+	const isDuplicate = info.versions.some(
+		(v) => v.name === name && v.version === version && v.modules === modules
```
Comment (ds300) [inline packages/utils/src/lib/version.ts]: can we make this also check that it's a nextjs dev env? otherwise i reckon this might produce some false negatives (bad)
