### PR TITLE
fix(dotcom): remove fairies submenu and watermark hiding

### LINKED ISSUE #7709: Fairies menu should not be visible in production
## Problem

The Fairies submenu in user settings is visible to all signed-in users on tldraw.com, including non-tldraw accounts. This menu item should not be visible in production environments. Additionally, when fairies are enabled (the default), the "made with tldraw" watermark is hidden via CSS.

## Steps to reproduce

1. Sign in to tldraw.com with a non-tldraw account (production environment)
2. Open the user settings menu (click your name in the sidebar)
3. Observe the "Fairies" submenu is visible with "Enable fairies" toggle
4. Note that the watermark in the bottom-right corner is hidden (because fairies are enabled by default)

## Expected behavior

- The Fairies submenu should not be visible in production
- The watermark should be visible for users without a business license

## Current behavior

The `FairiesSubmenu` component renders unconditionally for all signed-in users in production. The watermark is hidden via CSS when the `tla-fairies-enabled` class is present, which is tied to the local session state toggle.

## Relevant code

**FairiesSubmenu** (`apps/dotcom/client/src/tla/components/TlaSidebar/components/TlaSidebarUserSettingsMenu.tsx:75`):
- Renders without any environment or access checks

**Watermark hiding CSS** (`apps/dotcom/client/src/tla/styles/tla.css:338-340`):
```css
.tla.tla-fairies-enabled .tl-watermark_SEE-LICENSE {
    display: none;
}
```

**Class application** (`apps/dotcom/client/src/tla/providers/TlaRootProviders.tsx:114`):
- Applies `tla-fairies-enabled` class based on local session state

## Suggested fix

1. Hide the `FairiesSubmenu` component in production (use `isDevelopmentEnv` or similar check)
2. Alternatively, gate it behind proper fairy access checks using `useFairyAccess()`
3. Ensure watermark visibility is not affected by the local fairies toggle for users without proper access

### PR DESCRIPTION
**Pull request by kostyafarber**
In order to prevent unauthorized users from hiding the "made with tldraw" watermark, this PR removes the Fairies submenu from user settings and the CSS that hides the watermark.

The issue was that the fairies toggle used local storage state (`useAreFairiesEnabled()`) rather than server-side access validation, allowing any user to toggle the setting and hide the watermark. This conflated a local UI preference with a permissioned feature.

Closes #7709

### Change type

- [x] `bugfix`

### Test plan

1. Log in to tldraw.com as a user without a business license
2. Verify the Fairies submenu no longer appears in user settings
3. Verify the "made with tldraw" watermark remains visible

### Release notes

- Fixed an issue where the "made with tldraw" watermark could be hidden by unauthorized users via the Fairies menu

---

> [!NOTE]
> - **Fairies UI gating:** `TlaEditor.tsx` no longer uses `useAreFairiesEnabled`; `canControlFairies`/`shouldShowFairyUI` depend only on `useFairyAccess` and `useShouldShowFairies`.
> - **Removed user setting:** `TlaSidebarUserSettingsMenu.tsx` drops the Fairies submenu and related debug toggle.
> - **Watermark visibility:** Deleted `.tla-fairies-enabled` class usage and CSS that hid `.tl-watermark_SEE-LICENSE`; root providers no longer add that class.
> - **Session state cleanup:** Removed `fairiesEnabled` helpers from `local-session-state.ts` (getter, hook, toggle), keeping only debug flag.
> - **i18n cleanup:** Removed unused strings for "Enable fairies" and "Debug fairies" from `locales*.json`.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 382d587aff7fc7ab97968a18fb165cedd7dd96f2. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: apps/dotcom/client/src/tla/utils/local-session-state.ts [hunk 1]
```diff
@@ -154,10 +154,6 @@ export function getAreFairiesEnabled() {
 	return localSessionState.get().fairiesEnabled ?? true
 }
 
-export function useAreFairiesEnabled() {
-	return useValue('areFairiesEnabled', getAreFairiesEnabled, [])
-}
-
 export function toggleFairies(enabled?: boolean) {
```
Comment (mimecuvalo) [inline apps/dotcom/client/src/tla/utils/local-session-state.ts]: let's nix this

File: apps/dotcom/client/src/tla/utils/local-session-state.ts
Comment (mimecuvalo) [inline apps/dotcom/client/src/tla/utils/local-session-state.ts]: and nix this too
